# Generated by Django 4.2.1 on 2023-05-29 20:24

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('otch', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('height', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_summer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name='Категория трудности (лето)')),
                ('level_winter', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name='Категория трудности (зима)')),
                ('status_positions', models.CharField(choices=[('NE', 'News'), ('PE', 'Pending'), ('AC', 'Accepted'), ('RE', 'Rejected')], default='NE', max_length=2, verbose_name='Статус обработки')),
                ('name_obj', models.CharField(max_length=250, verbose_name='Название объекта')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testy.coordinates', verbose_name='Координаты')),
                ('info_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testy.author', verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('file_image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('connect_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testy.level', verbose_name='Привязать изображение к...')),
            ],
        ),
    ]
